export default function getCotizacionInicial() {
  return {
    id: 0,
    proveedor_id: '',
    file_nro: '',
    file_nombre: '',
    comprobante_id: '',
    fecha: '',
    estado_reserva: 0,
    estado_documentacion: 0,
    nro_pasajeros: 0,
    nro_ninio: 0,
    nro_adulto: 0,
    nro_estudiante: 0,
    destino_turistico_detalle: [],
    idioma_id: '',
    mercado_id: '',
    destino_turistico_id: '',
    pais_id: '',
    fecha_inicio: '',
    fecha_fin: '',
    nro_dias: 1,
    estado_cotizacion: 0,
    estado_reserva: 0,
    estado_documentacion: 0,
    costo_parcial: 0,
    descuento_estudiante: 0,
    descuento_ninio: 0,
    descuento_otro: 0,
    costo_total: 0,
    estado_activo: 1,

    Pasajeros: [],
    Servicios: [],
    PasajeroServicio: [],
  };
}